##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should 
# be placed in this file
#
##############################################################################
##############################################################################

name: Push Workflow

on:
  push:
    branches:
      - '**'   

jobs:

##############################################################################
# This section is added so that the most recent and valid level of 
# code coverage (post PR merge) is reported 
##############################################################################
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name : "Run JSDocs"   
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./lib
        recurse: true
        output_dir: out
    - name: Create pull request to test
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: './out'
        destination_repo: 'akshatgarg12/talawa-docs'
        destination_folder: 'docs/talawa-api'
        destination_base_branch: 'master'
        destination_head_branch: ${{ github.sha }}
        user_email: 'akshatarungarg78@gmail.com'
        user_name: 'akshatgarg12'
   
      

  Code-Coverage:
    name: Testing Application
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        mongodb-version: ['4.4']
    services:
      mongo:
        image: mongo
        options: >-
                --health-cmd mongo
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
        ports:
          - 27017:27017
    env:
      MONGO_DB_URL: mongodb://localhost:27017/talawa-test-db
      ACCESS_TOKEN_SECRET: eeb2137b1961a3da9e3736ea4a9ed1e77cb33a4fad8a153d364c2f04ec50eab7
      REFRESH_TOKEN_SECRET: 96d41e144e63475f7f753735b50305cd2857cc41c2f2570babdb948c10b77bc5
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: npm install

    - name: Start the Application
      run: npm run start-test-server-in-action

    - name: Sleep for 10s
      uses: juliangruber/sleep-action@v1
      with:
        time: 10s

    - name: Run the tests
      run: npm run test

    - name: Stop the Application
      run: npm run stop-test-server-in-action

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0    
